spring.application.name=MessegeService

# Server Configuration
server.port=8082

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ttvv_message
spring.data.mongodb.auto-index-creation=true

# Data Seeding Configuration
# Set to true to enable data seeding on startup
# Set to false to disable seeding (useful after first run)
app.data.seed.enabled=true
